### ISSUE TITLE
能否新增一个同类型xpath查找

### ISSUE THREAD

**Issue by Cdners** [mic1on/xpath-helper-plus#3]
http://www.lzbs.com.cn/ttnews/
新闻列表页通过精简xpath确实方便很多
但是比如 第一个和第二个新闻需要手动把下标[1]删除
//ul[@class='mlistDotBlack mrgt10']/li[1]/a
//ul[@class='mlistDotBlack mrgt10']/li[2]/a
如果有个功能输出是 //ul[@class='mlistDotBlack mrgt10']/li/a 就更方便了

**Comment by gt1226500986** [comment]
> http://www.lzbs.com.cn/ttnews/ 新闻列表页通过精简xpath确实方便很多 但是比如 第一个和第二个新闻需要手动把下标[1]删除 //ul[@Class='mlistDotBlack mrgt10']/li[1]/a //ul[@Class='mlistDotBlack mrgt10']/li[2]/a 如果有个功能输出是 //ul[@Class='mlistDotBlack mrgt10']/li/a 就更方便了

我也向往有这个功能

**Comment by gt1226500986** [comment]
![1700650678551](https://github.com/mic1on/xpath-helper-plus/assets/52158590/8c72b3d0-e746-431f-bf99-af2d89e2c0db)
![1700650712890](https://github.com/mic1on/xpath-helper-plus/assets/52158590/aef04f1d-a831-405d-a2db-7c3a0a5a23fe)
两个问题，使用解压包直接导入报错，解压后导入显示1.04

**Comment by memoryleilei** [comment]
请问作者，你实现这个功能，大概的思路是怎样的？好奇请教
